apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: revlab
  labels:
    app: nginx-proxy
data:
  nginx.conf: |
    worker_processes  1;
    events { worker_connections 1024; }

    http {
      upstream backend_python { server backend-python:8000; }
      upstream backend_php { server backend-php:9000; }

      server {
        listen 8080;

        # Example routes to exercise reverse-proxy behaviors
        location /py/ {
          proxy_pass http://backend_python/;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /php/ {
          proxy_pass http://backend_php/;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Default catcher
        location / {
          return 200 "nginx proxy is up\n";
        }
      }
    }
