x-default-logging: &default_logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  nginx:
    build: ../services/proxies/nginx
    profiles: ["nginx"]
    container_name: lab_nginx
    restart: unless-stopped
    logging: *default_logging
    command: ["/bin/sh", "-c", "apk add --no-cache tcpdump && exec /docker-entrypoint.sh nginx -g 'daemon off;'" ]
    # Mount config: allow override with NGINX_CONF
    volumes:
      - "${NGINX_CONF:-./services/proxies/nginx/conf/base.conf}:/etc/nginx/conf.d/default.conf:ro"
    networks: [front, back]
    ports:
      - "${NGINX_HOST_PORT:-8080}:80"

networks:
  front: {}
  back: {}
